name: Auto Renew and Start Bot

on:
  schedule:
    - cron: '0 2 */2 * *'
  workflow_dispatch: 

jobs:
  maintain:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests

      - name: Run Main Script
        env:
          MRTCLOUD_TOKEN: ${{ secrets.MRTCLOUD_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py

      - name: 🧹 clean up old workflow logs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600
